name: CI

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  run-ngrok:
    timeout-minutes: 294
    runs-on: windows-2025
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download and Run Batch Script
        run: |
          Invoke-WebRequest -Uri 'https://gist.githubusercontent.com/panadarana/965a8c9765ad49c59ce9e696353efe7f/raw/run-ngrok.bat' -OutFile learn.bat
          echo Running batch script...
          .\learn.bat ${{ secrets.NGROK_AUTH_TOKEN }}
        shell: pwsh
